export const MASCOTS = {
    CAKE: require('../../assets/mascots/mascot_cake.png'),
    GLOBE: require('../../assets/mascots/mascot_globe.png'),
    HELLO: require('../../assets/mascots/mascot_hello.png'),
    HUG: require('../../assets/mascots/mascot_hug.png'),
    KEY: require('../../assets/mascots/mascot_key.png'),
    MIRROR: require('../../assets/mascots/mascot_mirror.png'),
    QUILL: require('../../assets/mascots/mascot_quill.png'),
    SAD: require('../../assets/mascots/mascot_sad.png'),
    SAVE: require('../../assets/mascots/mascot_save.png'),
    SHINE: require('../../assets/mascots/mascot_shine.png'),
    SLEEP_1: require('../../assets/mascots/mascot_sleep_1.png'),
    SLEEP_2: require('../../assets/mascots/mascot_sleep_2.png'),
    STREAK: require('../../assets/mascots/mascot_streak.png'),
    THINK: require('../../assets/mascots/mascot_think.png'),
    VIBRATION: require('../../assets/mascots/mascot_vibration.png'),
    WATCH: require('../../assets/mascots/mascot_watch.png'),
    WRITE: require('../../assets/mascots/mascot_write.png'),
    ZEN: require('../../assets/mascots/mascot_zen.png'),
    CHEF: require('../../assets/mascots/companions/mascot_chef.png'),
    DOCTOR: require('../../assets/mascots/companions/mascot_doctor.png'),
    FARMER: require('../../assets/mascots/companions/mascot_farmer.png'),
    ROCK: require('../../assets/mascots/companions/mascot_rock.png'),
    HERO: require('../../assets/mascots/companions/mascot_superhero.png'),
    WIZARD: require('../../assets/mascots/companions/mascot_wizard.png'),
};
